blank_issues_enabled: false  # 禁用空白issue
contact_links:
  - name: "直接与作者沟通"
    url:  https://t.me/Omphalos2_bot
    about: "欢迎参与讨论"
warnings:
  - name: "提交Issue前的注意事项"
    about: "请在提交issue前，确保已阅读项目的README和相关文档，以避免重复的问题。请提供尽可能详细的信息，以帮助我们更好地理解和解决您的问题。尊重他人，保持礼貌，任何不当行为可能导致issue被关闭。如果您的issue涉及安全问题，请勿公开发布，直接联系作者。提交bug报告时，请附上重现步骤和相关环境信息。功能请求请描述清楚您的需求和预期效果。"
    url: ""
notice:
  - name: "必须使用 Issue 模板提交报告，否则将被关闭并删除"
    about: "为了更好地帮助您解决问题，请选择合适的Issue模板提交您的报告。不是为难你，而是为了更高效地处理问题。感谢您的理解与配合！"
    url: ""