blank_issues_enabled: false  # ç¦ç”¨ç©ºç™½issue
contact_links:
  - name: "å’Œä½œè€…å³æ—¶åé¦ˆé—®é¢˜ â„¹ï¸ Telegram"
    url: https://t.me/@Omphalos2_bot
    about: "æ¬¢è¿å‚ä¸è®¨è®º"
  - name: "åˆ›å»º ISSUE å‰å¿…è¯»"
    url: https://raw.githubusercontent.com/tvvocold/How-To-Ask-Questions-The-Smart-Way/refs/heads/master/README.md
    about: "è¯·å…ˆé˜…è¯»å¦‚ä½•é«˜æ•ˆæé—®"
  - name: "é¡¹ç›®ä¸»é¡µ ğŸ  GitHub"
    url: https://github.com/Mapleawaa/PVE-Tools-9
    about: "æŸ¥çœ‹é¡¹ç›®çš„æºä»£ç å’Œæ–‡æ¡£"
